### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by haydn-jones**

### CODE REVIEW

**Review by benpm — APPROVED** [review]
looks great, i just added a few minor things like some helpful links and screenshots in a table

**Comment by haydn-jones** [comment]
Can you fix the ordering of the table of contents after the changes?

**Comment by haydn-jones** [comment]
> looks great, i just added a few minor things like some helpful links and screenshots in a table

Can you fix the ordering of the table of contents after the changes?

**Comment by benpm** [comment]
> > looks great, i just added a few minor things like some helpful links and screenshots in a table
> 
> Can you fix the ordering of the table of contents after the changes?

oops my bad

fixed

**Pull request merged**
